version: "3"
services:
  aliyun-exporter:
    image: fengxsong/aliyun-exporter:v0.1.0
    volumes:
    - ../config.yaml:/etc/aliyun-exporter.yaml
    command:
    - serve
    - -c
    - /etc/aliyun-exporter.yaml
    environment:
    - ACCESS_KEY=${ACCESS_KEY}
    - ACCESS_KEY_SECRET=${ACCESS_KEY_SECRET}
    ports:
    - 9527:9527
    restart: always